# Generated by Django 4.0 on 2021-12-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_template',
        ),
    ]
