# Generated by Django 4.0 on 2021-12-10 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_image_book_book_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_template',
            field=models.ImageField(blank=True, null=True, upload_to='book/image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 17, 45, 25, 809792), null=True),
        ),
    ]
