# Generated by Django 4.0 on 2021-12-10 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0005_alter_book_book_template_alter_book_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 21, 42, 50, 381789), null=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 21, 42, 50, 381789), null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('book_template', models.ImageField(blank=True, null=True, upload_to='book/image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
